/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WelcomeMessage {
        /**
          * The app name
         */
        "app": string;
        /**
          * some text to dasherize
         */
        "text": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWelcomeMessageElement extends Components.WelcomeMessage, HTMLStencilElement {
    }
    var HTMLWelcomeMessageElement: {
        prototype: HTMLWelcomeMessageElement;
        new (): HTMLWelcomeMessageElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "welcome-message": HTMLWelcomeMessageElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WelcomeMessage {
        /**
          * The app name
         */
        "app"?: string;
        /**
          * some text to dasherize
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "welcome-message": WelcomeMessage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "welcome-message": LocalJSX.WelcomeMessage & JSXBase.HTMLAttributes<HTMLWelcomeMessageElement>;
        }
    }
}
